// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

/**
 * @notice Standard interface for ZK Verifier contracts generated by snarkjs.
 * We use two separate interfaces to handle different public signal counts (4 and 6).
 */
interface IVerifier4 {
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[4] calldata input
    ) external view returns (bool);
}

interface IVerifier6 {
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[6] calldata input
    ) external view returns (bool);
}

/**
 * @title VanishGuard
 * @notice A security gateway and policy enforcer for the Vanish privacy pool.
 */
contract VanishGuard {
    // ─────────────────────────────────────────────
    //  Types
    // ─────────────────────────────────────────────

    struct Policy {
        uint32  minBatchSize;
        uint32  maxBatchSize;
        uint32  minDelaySeconds;
        uint32  maxDelayMinutes;
        uint32  maxWaitMinutes;
        uint256[] allowedDenominations;
        string  version;
    }

    // ─────────────────────────────────────────────
    //  Storage
    // ─────────────────────────────────────────────

    address public owner;
    address public decisionSigner;
    Policy  public policy;
    bytes32 public currentMerkleRoot; 
    mapping(bytes32 => bool) public rootHistory;

    address public shieldVerifier;
    address public withdrawVerifier;
    address public exclusionVerifier;

    mapping(uint256 => bool) public nullifiers;
    mapping(bytes32 => bool) public decisionEnvelopeSeen;

    uint256 public totalBatchesApproved;
    uint256 public totalDepositsShielded;

    // ─────────────────────────────────────────────
    //  Events
    // ─────────────────────────────────────────────

    event PolicyUpdated(string indexed version, uint32 minBatchSize, uint32 maxBatchSize, uint32 minDelaySeconds, uint256 denominationCount);
    event BatchApproved(bytes32 indexed merkleRoot, bytes32 indexed auditHash, uint32 batchSize, uint256 delayMs, uint256 timestamp);
    event DecisionEnvelopeAnchored(bytes32 indexed decisionEnvelopeHash, address indexed recoveredSigner, bytes32 signatureHash, uint256 timestamp);
    event DecisionSignerUpdated(address indexed oldSigner, address indexed newSigner);
    event DepositShielded(bytes32 indexed commitment, uint256 amountTinybars, uint256 timestamp);
    event WithdrawalExecuted(uint256 indexed nullifierHash, address indexed recipient, uint256 amountTinybars, uint256 timestamp);
    event InternalSwapExecuted(uint256 indexed nullifierHash, bytes32 indexed newCommitment, uint256 amountTinybars, uint256 timestamp);

    // ─────────────────────────────────────────────
    //  Errors
    // ─────────────────────────────────────────────

    error OnlyOwner();
    error BatchSizeTooSmall(uint32 got, uint32 min);
    error BatchSizeTooLarge(uint32 got, uint32 max);
    error DelayTooShort(uint256 gotMs, uint256 minMs);
    error DelayTooLong(uint256 gotMs, uint256 maxMs);
    error ExecuteConditionNotMet(uint32 queueSize, uint32 minBatch, uint256 queueAgeMs, uint256 maxWaitMs);
    error DenominationNotAllowed(uint256 amountTinybars);
    error NullifierAlreadyUsed(uint256 nullifierHash);
    error EmptyMerkleRoot();
    error EmptyAuditHash();
    error EmptyDecisionEnvelopeHash();
    error DecisionEnvelopeReplay(bytes32 envelopeHash);
    error InvalidDecisionSignature(address recovered, address expected);
    error InvalidDecisionSigner(address signer);
    error InvalidWithdrawProof();
    error WithdrawalFailed();
    error RootNotFound();

    // ─────────────────────────────────────────────
    //  Constructor
    // ─────────────────────────────────────────────

    constructor(
        uint32  minBatchSize,
        uint32  maxBatchSize,
        uint32  minDelaySeconds,
        uint32  maxDelayMinutes,
        uint32  maxWaitMinutes,
        uint256[] memory allowedDenoms,
        string  memory policyVersion
    ) {
        owner = msg.sender;
        decisionSigner = msg.sender;
        _setPolicy(minBatchSize, maxBatchSize, minDelaySeconds, maxDelayMinutes, maxWaitMinutes, allowedDenoms, policyVersion);
    }

    // ─────────────────────────────────────────────
    //  Admin
    // ─────────────────────────────────────────────

    modifier onlyOwner() {
        if (msg.sender != owner) revert OnlyOwner();
        _;
    }

    function setPolicy(uint32 min, uint32 max, uint32 minD, uint32 maxD, uint32 maxW, uint256[] calldata denoms, string calldata ver) external onlyOwner {
        _setPolicy(min, max, minD, maxD, maxW, denoms, ver);
    }

    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "VanishGuard: zero address");
        owner = newOwner;
    }

    function setDecisionSigner(address newSigner) external onlyOwner {
        if (newSigner == address(0)) revert InvalidDecisionSigner(newSigner);
        address oldSigner = decisionSigner;
        decisionSigner = newSigner;
        emit DecisionSignerUpdated(oldSigner, newSigner);
    }

    function setVerifiers(address _shield, address _withdraw, address _exclusion) external onlyOwner {
        shieldVerifier = _shield;
        withdrawVerifier = _withdraw;
        exclusionVerifier = _exclusion;
    }

    // ─────────────────────────────────────────────
    //  Core: Batch Submission
    // ─────────────────────────────────────────────

    function submitBatch(uint32 size, uint256 delay, uint256 age, bytes32[] calldata roots, bytes32 audit) external {
        _submitBatchInternal(size, delay, age, roots, audit);
    }

    function submitBatchWithDecision(uint32 size, uint256 delay, uint256 age, bytes32[] calldata roots, bytes32 audit, bytes32 envHash, bytes calldata sig) external {
        if (envHash == bytes32(0)) revert EmptyDecisionEnvelopeHash();
        if (decisionEnvelopeSeen[envHash]) revert DecisionEnvelopeReplay(envHash);
        address recovered = _recoverDecisionSigner(envHash, sig);
        if (recovered != decisionSigner) revert InvalidDecisionSignature(recovered, decisionSigner);

        _submitBatchInternal(size, delay, age, roots, audit);
        decisionEnvelopeSeen[envHash] = true;
        emit DecisionEnvelopeAnchored(envHash, recovered, keccak256(sig), block.timestamp);
    }

    function validateBatch(uint32 size, uint256 delay, uint256 age) external view returns (bool valid, string memory reason) {
        uint256 minD = uint256(policy.minDelaySeconds) * 1000;
        uint256 maxD = uint256(policy.maxDelayMinutes) * 60 * 1000;
        uint256 maxW = uint256(policy.maxWaitMinutes) * 60 * 1000;

        if (size < policy.minBatchSize) return (false, "batchSize too small");
        if (size > policy.maxBatchSize) return (false, "batchSize too large");
        if (delay < minD) return (false, "delay too short");
        if (delay > maxD) return (false, "delay too long");
        if (size < policy.minBatchSize && age < maxW) return (false, "execute condition not met");

        return (true, "");
    }

    // ─────────────────────────────────────────────
    //  Core: Shield / Withdraw
    // ─────────────────────────────────────────────

    receive() external payable {}

    function shieldDeposit(
        uint256 amountTinybars,
        bytes32 commitment,
        uint256 nullifierHash,
        bytes32 root,
        uint256[2] calldata proofA,
        uint256[2][2] calldata proofB,
        uint256[2] calldata proofC
    ) external payable {
        _requireAllowedDenomination(amountTinybars);
        require(msg.value >= amountTinybars, "VanishGuard: Insufficient HBAR");
        if (root != currentMerkleRoot && !rootHistory[root] && root != bytes32(0)) revert RootNotFound();
        if (nullifiers[nullifierHash]) revert NullifierAlreadyUsed(nullifierHash);

        if (shieldVerifier != address(0)) {
            uint256[4] memory inputs;
            inputs[0] = nullifierHash;
            inputs[1] = uint256(commitment);
            inputs[2] = uint256(uint128(uint256(root)));
            inputs[3] = uint256(uint128(uint256(root) >> 128));
            
            bool valid = IVerifier4(shieldVerifier).verifyProof(proofA, proofB, proofC, inputs);
            if (!valid) revert InvalidWithdrawProof();
        }

        nullifiers[nullifierHash] = true;
        totalDepositsShielded++;
        emit DepositShielded(commitment, amountTinybars, block.timestamp);
    }

    function withdraw(
        uint256 amountTinybars,
        address payable recipient,
        uint256 nullifierHash,
        bytes32 commitment,
        bytes32 root,
        uint256[2] calldata proofA,
        uint256[2][2] calldata proofB,
        uint256[2] calldata proofC
    ) external {
        if (root != currentMerkleRoot && !rootHistory[root]) revert RootNotFound();
        if (nullifiers[nullifierHash]) revert NullifierAlreadyUsed(nullifierHash);

        if (withdrawVerifier != address(0)) {
            uint256[6] memory inputs;
            inputs[0] = nullifierHash;
            inputs[1] = uint256(commitment);
            inputs[2] = uint256(uint128(uint256(root)));
            inputs[3] = uint256(uint128(uint256(root) >> 128));
            inputs[4] = uint256(uint160(address(recipient)));
            inputs[5] = amountTinybars;

            bool valid = IVerifier6(withdrawVerifier).verifyProof(proofA, proofB, proofC, inputs);
            if (!valid) revert InvalidWithdrawProof();
        }

        nullifiers[nullifierHash] = true;
        (bool success, ) = recipient.call{value: amountTinybars}("");
        if (!success) revert WithdrawalFailed();
        emit WithdrawalExecuted(nullifierHash, recipient, amountTinybars, block.timestamp);
    }

    /**
     * @notice Execute an internal commitment-to-commitment swap (Shielded Transfer)
     * @dev This is the core of Vanish privacy - funds stay in pool, only ownership changes
     * @param amountTinybars Amount being transferred
     * @param nullifierHash Nullifier of the source commitment
     * @param sourceCommitment Source commitment being spent
     * @param newCommitment New commitment for the recipient
     * @param root Merkle root
     * @param proofA ZK proof part A
     * @param proofB ZK proof part B
     * @param proofC ZK proof part C
     */
    function internalSwap(
        uint256 amountTinybars,
        uint256 nullifierHash,
        bytes32 sourceCommitment,
        bytes32 newCommitment,
        bytes32 root,
        uint256[2] calldata proofA,
        uint256[2][2] calldata proofB,
        uint256[2] calldata proofC
    ) external {
        if (root != currentMerkleRoot && !rootHistory[root]) revert RootNotFound();
        if (nullifiers[nullifierHash]) revert NullifierAlreadyUsed(nullifierHash);
        if (newCommitment == bytes32(0)) revert EmptyMerkleRoot();

        // Verify ZK proof - recipient is 0 for internal swaps (funds stay in pool)
        if (withdrawVerifier != address(0)) {
            uint256[6] memory inputs;
            inputs[0] = nullifierHash;
            inputs[1] = uint256(sourceCommitment);
            inputs[2] = uint256(uint128(uint256(root)));
            inputs[3] = uint256(uint128(uint256(root) >> 128));
            inputs[4] = 0; // recipient = 0 means internal swap (funds stay in pool)
            inputs[5] = amountTinybars;

            bool valid = IVerifier6(withdrawVerifier).verifyProof(proofA, proofB, proofC, inputs);
            if (!valid) revert InvalidWithdrawProof();
        }

        nullifiers[nullifierHash] = true;

        // Note: In a full implementation, newCommitment would be added to Merkle tree
        // For now, we emit the event so the Pool Manager can track it
        emit InternalSwapExecuted(nullifierHash, newCommitment, amountTinybars, block.timestamp);
    }

    // ─────────────────────────────────────────────
    //  Internal / Helpers
    // ─────────────────────────────────────────────

    function _setPolicy(uint32 min, uint32 max, uint32 minD, uint32 maxD, uint32 maxW, uint256[] memory allowed, string memory ver) internal {
        policy.minBatchSize = min;
        policy.maxBatchSize = max;
        policy.minDelaySeconds = minD;
        policy.maxDelayMinutes = maxD;
        policy.maxWaitMinutes = maxW;
        policy.version = ver;
        delete policy.allowedDenominations;
        for (uint i = 0; i < allowed.length; i++) policy.allowedDenominations.push(allowed[i]);
        emit PolicyUpdated(ver, min, max, minD, allowed.length);
    }

    function _submitBatchInternal(uint32 size, uint256 dMs, uint256 aMs, bytes32[] calldata roots, bytes32 audit) internal {
        if (size < policy.minBatchSize) revert BatchSizeTooSmall(size, policy.minBatchSize);
        if (size > policy.maxBatchSize) revert BatchSizeTooLarge(size, policy.maxBatchSize);
        if (roots.length == 0) revert EmptyMerkleRoot();

        for (uint256 i = 0; i < roots.length; i++) {
            bytes32 root = roots[i];
            if (root == bytes32(0)) revert EmptyMerkleRoot();
            rootHistory[root] = true;
            currentMerkleRoot = root; // Last one becomes current, but all are valid via rootHistory
            emit BatchApproved(root, audit, size, dMs, block.timestamp);
        }
        totalBatchesApproved++;
    }

    function _requireAllowedDenomination(uint256 amt) internal view {
        uint256[] storage denoms = policy.allowedDenominations;
        if (denoms.length == 0) return;
        for (uint i = 0; i < denoms.length; i++) if (denoms[i] == amt) return;
        revert DenominationNotAllowed(amt);
    }

    function _recoverDecisionSigner(bytes32 digest, bytes calldata sig) internal pure returns (address) {
        if (sig.length != 65) return address(0);
        bytes32 r; bytes32 s; uint8 v;
        assembly {
            r := calldataload(sig.offset)
            s := calldataload(add(sig.offset, 32))
            v := byte(0, calldataload(add(sig.offset, 64)))
        }
        if (v < 27) v += 27;
        return ecrecover(digest, v, r, s);
    }
}
